### ISSUE TITLE
Transferring...

### ISSUE THREAD

**Issue by TheDragonRing** [BoxOfDevs/BlackHole#1]
Just saying now that you transferred to BOD we'll need to change the author details and README and all that, but you will get proper credit @LittleBigMC

**Comment by LittleBigMC** [comment]
Ok

**Comment by LittleBigMC** [comment]
Ive done that now. Should i close this?? XD

**Comment by TheDragonRing** [comment]
Yeah sure, I'll probly still do README and Main.php edits later anyway xD
